devs:
  twitter-search:
    order: 1
    term: "@chicago"

  # github-commits:
    # order: 2
    # username: "ravenduo"
    # repository: "sc-pingpong"

  cta-bus-tracker:
    order: 3
    route-number: 29
    stop-id: 2355

  clock:
    interval: 30
    order: 4
    timezones:
      - timezone: "America/Chicago"
        name: "Chicago"
      # - timezone: "UTC"
        # name: "UTC"

  cta-train-tracker:
    order: 5
    map-id: "12345"
    api-key: "abc123"
    stop: "Harrison"
    stop: "Roosevelt"

  google-weather:
    city: "Chicago"

  #nagios-problems:
    #order: 6
    #host: "https://url.example.com"
    #username: "yourusername"
    #password: "yourpassword"

  #jenkins-builds:
    #order: 7
    #url: "https://url.example.com"
    #username: "yourusername"
    #password: "yourpassword"

  #elovation-game:
    #order: 8
    #url: "http://url.example.com"
    #game-id: "3"
    #username: "yourusername"
    #password: "yourpassword"

  #jukebox:
    #order: 9
    #url: "http://url.example.com"

  dark-sky:
    order: 10
    api-key: bf4410b69c742fcf5acce93fdb9f0768api-key
    lat: 41.90
    lon: 87.65
    interval: 60