devs:
  # twitter-search:
    # order: 1
    # term: "@chicago"

  # github-commits:
    # order: 2
    # username: "ravenduo"
    # repository: "sc-pingpong"

  # cta-bus-tracker:
  #   order: 3
  #   route-number: 29
  #   stop-id: 2355

  clock:
    interval: 30
    order: 4
    timezones:
      - timezone: "America/Chicago"
        name: "Chicago"
      # - timezone: "UTC"
        # name: "UTC"

  # cta-train-tracker:
  #   order: 5
  #   map-id: "40330"
  #   api-key: "c5914e33ab5b4436b7ca9e34207c89d2"

  cta-train-tracker:
    order: 6
    map-id: "40460"
    api-key: "c5914e33ab5b4436b7ca9e34207c89d2"

  # google-weather:
    # city: "Chicago"

  # jenkins-builds:
  #   order: 7
  #   url: "http://deploy.emp.sittercity.com:8080"
    #username: "yourusername"
    #password: "yourpassword"

  elovation-game:
    order: 8
    url: "http://sc-pingpong.herokuapp.com"
    game-id: "4"
    username: "sittercity"
    password: "pingpong"

  elovation-games:
    order: 7
    url: "http://sc-pingpong.herokuapp.com"
    game-id: "3"
    username: "sittercity"
    password: "pingpong"

  # elovation-game:
  #   order: 7
  #   url: "http://sc-pingpong.herokuapp.com"
  #   game-id: "3"
  #   username: "sittercity"
  #   password: "pingpong"

  #jukebox:
    #order: 9
    #url: "http://url.example.com"